# Generated by Django 5.2.4 on 2025-07-23 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(help_text="The full name of the shop, e.g., 'Duka la coed ngongona'", max_length=255, verbose_name='Shop Name')),
                ('abbrev', models.CharField(help_text="A short, unique abbreviation for the shop, e.g., 'CIVE'", max_length=50, unique=True, verbose_name='Abbreviation')),
                ('comment', models.TextField(blank=True, help_text='Any additional notes about the shop', null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this shop was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['names'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Temporarily Unavailable')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('restock_date', models.DateField(default=django.utils.timezone.now, verbose_name='Last Restock Date')),
                ('expiry_date', models.DateField(blank=True, default=None, null=True, verbose_name='Expiry Date')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Additional Notes')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
