# Generated by Django 5.2.4 on 2026-01-23 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_cart_options_alter_cart_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-qty'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_shop_id_4cac30_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_name_0dcee6_idx',
        ),
        migrations.RemoveIndex(
            model_name='sales',
            name='shops_sales_created_1e814f_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_names_92acd5_idx',
        ),
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Temporarily Unavailable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restock_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Last Restock Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item price'),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale profit'),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item qty'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Sale amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.CharField(default='n/a', max_length=255, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='profit',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='abbrev',
            field=models.CharField(help_text="A short, unique abbreviation for the shop, e.g., 'CIVE'", max_length=50, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='comment',
            field=models.TextField(blank=True, help_text='Any additional notes about the shop', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date and time when this shop was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='names',
            field=models.CharField(help_text="The full name of the shop, e.g., 'Duka la coed ngongona'", max_length=255, verbose_name='Shop Name'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'product'], name='shops_cart_user_id_3cd5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_deleted', 'is_hidden', 'qty'], name='shops_produ_shop_id_bd407b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shops_produ_name_495435_idx'),
        ),
        migrations.AddIndex(
            model_name='sale_items',
            index=models.Index(fields=['sale', 'product'], name='shops_sale__sale_id_2b5b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['shop', 'user', 'created_at'], name='shops_sales_shop_id_aabf70_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['names', 'abbrev'], name='shops_shop_names_23d4f0_idx'),
        ),
    ]
