# Generated by Django 5.2.4 on 2026-01-23 07:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_cart_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_name_495435_idx',
        ),
        migrations.RemoveIndex(
            model_name='sales',
            name='shops_sales_shop_id_aabf70_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_names_23d4f0_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restock_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last Restock Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Item price'),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='profit',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Sale profit'),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='qty',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Item qty'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.CharField(db_index=True, default='n/a', max_length=255, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='abbrev',
            field=models.CharField(db_index=True, help_text="A short, unique abbreviation for the shop, e.g., 'CIVE'", max_length=50, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='names',
            field=models.CharField(db_index=True, help_text="The full name of the shop, e.g., 'Duka la coed ngongona'", max_length=255, verbose_name='Shop Name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_deleted'], name='shops_produ_shop_id_4b88bc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted', 'name'], name='shops_produ_is_dele_b31628_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['expiry_date', 'is_deleted'], name='shops_produ_expiry__7fa86b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale_items',
            index=models.Index(fields=['product'], name='shops_sale__product_b400f6_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['shop', 'created_at'], name='shops_sales_shop_id_8cd531_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['created_at', 'shop'], name='shops_sales_created_1e814f_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at', 'names'], name='shops_shop_created_3019d4_idx'),
        ),
    ]
