# Generated by Django 5.2.4 on 2026-01-23 09:59

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_product_shops_produ_name_495435_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='shops_cart_user_id_3cd5fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_shop_id_bd407b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_shop_id_4b88bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_is_dele_b31628_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shops_produ_expiry__7fa86b_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale_items',
            name='shops_sale__product_b400f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='sales',
            name='shops_sales_shop_id_8cd531_idx',
        ),
        migrations.RemoveIndex(
            model_name='sales',
            name='shops_sales_created_1e814f_idx',
        ),
        migrations.RemoveIndex(
            model_name='shop',
            name='shops_shop_created_3019d4_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restock_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Last Restock Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item price'),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale profit'),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item qty'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale amount'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.CharField(default='n/a', max_length=255, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='abbrev',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='names',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Shop Name'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['-created_at', 'shop'], name='shops_sales_created_ea1503_idx'),
        ),
    ]
