# Generated by Django 5.2.4 on 2025-08-01 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0001_initial'),
        ('shops', '0002_cart_sales_sale_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='debt_shop', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='debts',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='debt_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lipanamba',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lipa_shop', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='lipanamba',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='lipa_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loans',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='loan_shop', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='loans',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='loan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selcompay',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sel_shop', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='selcompay',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sel_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
