# Generated by Django 5.2.4 on 2025-12-04 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0002_debts_shop_debts_user_lipanamba_shop_lipanamba_user_and_more'),
        ('shops', '0002_cart_sales_sale_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mauzo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('dates', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mauzo_shop', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mauzo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
