# Generated by Django 5.2.4 on 2025-07-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0002_alter_debts_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
