# Generated by Django 5.2.4 on 2025-12-25 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0003_mauzo'),
        ('shops', '0002_cart_sales_sale_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debts',
            index=models.Index(fields=['deleted', 'created_at'], name='miamala_deb_deleted_cd88b3_idx'),
        ),
        migrations.AddIndex(
            model_name='debts',
            index=models.Index(fields=['deleted', 'shop'], name='miamala_deb_deleted_a8c195_idx'),
        ),
        migrations.AddIndex(
            model_name='debts',
            index=models.Index(fields=['name'], name='miamala_deb_name_3e5513_idx'),
        ),
        migrations.AddIndex(
            model_name='debts',
            index=models.Index(fields=['-created_at'], name='miamala_deb_created_c2a64f_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['deleted', 'dates'], name='miamala_exp_deleted_ff74a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['deleted', 'shop'], name='miamala_exp_deleted_c75afe_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['title'], name='miamala_exp_title_ac17b7_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['-dates'], name='miamala_exp_dates_d97ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='lipanamba',
            index=models.Index(fields=['deleted', 'created_at'], name='miamala_lip_deleted_7166c0_idx'),
        ),
        migrations.AddIndex(
            model_name='lipanamba',
            index=models.Index(fields=['deleted', 'shop'], name='miamala_lip_deleted_a22554_idx'),
        ),
        migrations.AddIndex(
            model_name='lipanamba',
            index=models.Index(fields=['name'], name='miamala_lip_name_2d75d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lipanamba',
            index=models.Index(fields=['-created_at'], name='miamala_lip_created_c70e65_idx'),
        ),
        migrations.AddIndex(
            model_name='loans',
            index=models.Index(fields=['deleted', 'created_at'], name='miamala_loa_deleted_874749_idx'),
        ),
        migrations.AddIndex(
            model_name='loans',
            index=models.Index(fields=['deleted', 'shop'], name='miamala_loa_deleted_fc7d30_idx'),
        ),
        migrations.AddIndex(
            model_name='loans',
            index=models.Index(fields=['name'], name='miamala_loa_name_72366f_idx'),
        ),
        migrations.AddIndex(
            model_name='loans',
            index=models.Index(fields=['-created_at'], name='miamala_loa_created_0c643b_idx'),
        ),
        migrations.AddIndex(
            model_name='mauzo',
            index=models.Index(fields=['deleted', 'dates'], name='miamala_mau_deleted_c38549_idx'),
        ),
        migrations.AddIndex(
            model_name='mauzo',
            index=models.Index(fields=['deleted', 'shop'], name='miamala_mau_deleted_dac6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='mauzo',
            index=models.Index(fields=['-dates'], name='miamala_mau_dates_fe9066_idx'),
        ),
        migrations.AddIndex(
            model_name='selcompay',
            index=models.Index(fields=['deleted', 'created_at'], name='miamala_sel_deleted_1d48aa_idx'),
        ),
        migrations.AddIndex(
            model_name='selcompay',
            index=models.Index(fields=['deleted', 'shop'], name='miamala_sel_deleted_dc631f_idx'),
        ),
        migrations.AddIndex(
            model_name='selcompay',
            index=models.Index(fields=['name'], name='miamala_sel_name_e0f23e_idx'),
        ),
        migrations.AddIndex(
            model_name='selcompay',
            index=models.Index(fields=['-created_at'], name='miamala_sel_created_2f753f_idx'),
        ),
    ]
