# Generated by Django 5.2.4 on 2026-01-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0004_debts_miamala_deb_deleted_cd88b3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipanamba',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='selcompay',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
