# Generated by Django 5.2.4 on 2026-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0005_lipanamba_profit_selcompay_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mauzo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
