# Generated by Django 5.2.4 on 2026-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miamala', '0006_expenses_updated_at_mauzo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mauzo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
