# Generated by Django 5.2.4 on 2025-07-23 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_cart_sales_sale_items'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='customuser_shop_id_dc19ea_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(default=1, help_text='The shop this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shops.shop', verbose_name='Shop'),
        ),
    ]
