# Generated by Django 5.2.4 on 2025-07-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shops', '0002_cart_sales_sale_items'),
        ('users', '0002_remove_customuser_customuser_shop_id_dc19ea_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(help_text='The shop this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shops.shop', verbose_name='Shop'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['shop'], name='customuser_shop_id_dc19ea_idx'),
        ),
    ]
