# Generated by Django 5.2.4 on 2026-01-22 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crips', '0002_crips_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crips',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='crips',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Crips type'),
        ),
        migrations.AddIndex(
            model_name='crips',
            index=models.Index(fields=['name', 'created_at'], name='crips_crips_name_e60404_idx'),
        ),
    ]
